development:
    host: 'localhost'
    port: 27017
    dbname: 'dixte_analytics_development'

test:
    host: 'localhost'
    port: 27017
    dbname: 'dixte_analytics_test'

production:
    host: 'localhost'
    port: 27017
    dbname: 'dixte_analytics_production'
